export const initialTransactions = [
  {
    id: 1,
    date: "2024-01-12",
    description: "Salary",
    amount: 58000,
    category: "Income",
    type: "income",
  },
  {
    id: 2,
    date: "2024-01-14",
    description: "Groceries",
    amount: 2200,
    category: "Food",
    type: "expense",
  },
  {
    id: 3,
    date: "2024-02-01",
    description: "Rent",
    amount: 14500,
    category: "Housing",
    type: "expense",
  },
  {
    id: 4,
    date: "2024-02-08",
    description: "Metro Pass",
    amount: 900,
    category: "Transport",
    type: "expense",
  },
  {
    id: 5,
    date: "2024-03-05",
    description: "Freelance Project",
    amount: 14000,
    category: "Income",
    type: "income",
  },
  {
    id: 6,
    date: "2024-03-07",
    description: "Movie Night",
    amount: 650,
    category: "Entertainment",
    type: "expense",
  },
  {
    id: 7,
    date: "2024-04-02",
    description: "Electricity Bill",
    amount: 1800,
    category: "Other",
    type: "expense",
  },
  {
    id: 8,
    date: "2024-04-12",
    description: "Salary",
    amount: 59000,
    category: "Income",
    type: "income",
  },
  {
    id: 9,
    date: "2024-05-03",
    description: "Grocery Run",
    amount: 2400,
    category: "Food",
    type: "expense",
  },
  {
    id: 10,
    date: "2024-05-20",
    description: "Dining Out",
    amount: 1300,
    category: "Food",
    type: "expense",
  },
  {
    id: 11,
    date: "2024-06-01",
    description: "Rent",
    amount: 15000,
    category: "Housing",
    type: "expense",
  },
  {
    id: 12,
    date: "2024-06-18",
    description: "Bonus",
    amount: 8000,
    category: "Income",
    type: "income",
  },
  {
    id: 13,
    date: "2024-08-09",
    description: "Gym Membership",
    amount: 1200,
    category: "Other",
    type: "expense",
  },
  {
    id: 14,
    date: "2024-10-01",
    description: "Rent",
    amount: 15500,
    category: "Housing",
    type: "expense",
  },
  {
    id: 15,
    date: "2024-12-24",
    description: "Holiday Shopping",
    amount: 5200,
    category: "Entertainment",
    type: "expense",
  },
  {
    id: 16,
    date: "2025-01-12",
    description: "Salary",
    amount: 61000,
    category: "Income",
    type: "income",
  },
  {
    id: 17,
    date: "2025-02-10",
    description: "Car Service",
    amount: 4800,
    category: "Transport",
    type: "expense",
  },
  {
    id: 18,
    date: "2025-03-15",
    description: "Concert",
    amount: 2500,
    category: "Entertainment",
    type: "expense",
  },
  {
    id: 19,
    date: "2025-05-09",
    description: "Side Project",
    amount: 11000,
    category: "Income",
    type: "income",
  },
  {
    id: 20,
    date: "2025-07-04",
    description: "Vacation Travel",
    amount: 9000,
    category: "Transport",
    type: "expense",
  },
  {
    id: 21,
    date: "2025-09-22",
    description: "Home Repairs",
    amount: 3700,
    category: "Housing",
    type: "expense",
  },
  {
    id: 22,
    date: "2025-11-05",
    description: "Gadgets",
    amount: 4600,
    category: "Other",
    type: "expense",
  },
  {
    id: 23,
    date: "2026-01-12",
    description: "Salary",
    amount: 64000,
    category: "Income",
    type: "income",
  },
  {
    id: 24,
    date: "2026-02-14",
    description: "Dining Out",
    amount: 1700,
    category: "Food",
    type: "expense",
  },
  {
    id: 25,
    date: "2026-03-28",
    description: "Freelance Project",
    amount: 12500,
    category: "Transport",
    type: "expense",
  },
  {
    id: 26,
    date: "2026-03-29",
    description: "Groceries",
    amount: 2500,
    category: "Food",
    type: "expense",
  },
  {
    id: 27,
    date: "2026-03-30",
    description: "Rent",
    amount: 16000,
    category: "Housing",
    type: "expense",
  },
  {
    id: 28,
    date: "2026-04-01",
    description: "Transport",
    amount: 900,
    category: "Transport",
    type: "expense",
  },
  {
    id: 29,
    date: "2026-04-03",
    description: "Streaming Subscription",
    amount: 499,
    category: "Entertainment",
    type: "expense",
  },
  {
    id: 30,
    date: "2024-01-20",
    description: "Coffee",
    amount: 180,
    category: "Food",
    type: "expense",
  },
  {
    id: 31,
    date: "2024-02-22",
    description: "Medical Checkup",
    amount: 2100,
    category: "Other",
    type: "expense",
  },
  {
    id: 32,
    date: "2024-03-18",
    description: "Freelance Bonus",
    amount: 6000,
    category: "Income",
    type: "income",
  },
  {
    id: 33,
    date: "2024-05-28",
    description: "Fuel",
    amount: 1500,
    category: "Transport",
    type: "expense",
  },
  {
    id: 34,
    date: "2024-07-10",
    description: "Home Supplies",
    amount: 2300,
    category: "Housing",
    type: "expense",
  },
  {
    id: 35,
    date: "2024-09-14",
    description: "Movie Tickets",
    amount: 800,
    category: "Entertainment",
    type: "expense",
  },
  {
    id: 36,
    date: "2024-11-11",
    description: "Freelance Project",
    amount: 9500,
    category: "Income",
    type: "income",
  },
  {
    id: 37,
    date: "2025-01-22",
    description: "Groceries",
    amount: 2600,
    category: "Food",
    type: "expense",
  },
  {
    id: 38,
    date: "2025-02-27",
    description: "Internet Bill",
    amount: 999,
    category: "Other",
    type: "expense",
  },
  {
    id: 39,
    date: "2025-03-05",
    description: "Freelance Project",
    amount: 13000,
    category: "Income",
    type: "income",
  },
  {
    id: 40,
    date: "2025-04-18",
    description: "Taxi",
    amount: 600,
    category: "Transport",
    type: "expense",
  },
  {
    id: 41,
    date: "2025-06-02",
    description: "Rent",
    amount: 15800,
    category: "Housing",
    type: "expense",
  },
  {
    id: 42,
    date: "2025-07-19",
    description: "Dinner",
    amount: 1400,
    category: "Food",
    type: "expense",
  },
  {
    id: 43,
    date: "2025-08-23",
    description: "Side Project",
    amount: 9000,
    category: "Income",
    type: "income",
  },
  {
    id: 44,
    date: "2025-10-12",
    description: "Furniture",
    amount: 5200,
    category: "Housing",
    type: "expense",
  },
  {
    id: 45,
    date: "2025-12-02",
    description: "Year-end Bonus",
    amount: 15000,
    category: "Income",
    type: "income",
  },
  {
    id: 46,
    date: "2026-01-08",
    description: "Groceries",
    amount: 2400,
    category: "Food",
    type: "expense",
  },
  {
    id: 47,
    date: "2026-02-05",
    description: "Bus Pass",
    amount: 1200,
    category: "Transport",
    type: "expense",
  },
  {
    id: 48,
    date: "2026-02-22",
    description: "Dining Out",
    amount: 1600,
    category: "Food",
    type: "expense",
  },
  {
    id: 49,
    date: "2026-03-10",
    description: "Gadget Purchase",
    amount: 7200,
    category: "Other",
    type: "expense",
  },
  {
    id: 50,
    date: "2026-04-04",
    description: "Freelance Project",
    amount: 13500,
    category: "Income",
    type: "income",
  },
];

export const categories = [
  "Income",
  "Food",
  "Housing",
  "Transport",
  "Entertainment",
  "Other",
];
